[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
allow = [
    "Apache-2.0",
    "MIT",
    "Unlicense",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "cfg-if", version = "0.1.10" },
    { name = "core-foundation", version = "0.7.0" },
    { name = "core-foundation-sys", version = "0.7.0" },
    { name = "core-graphics", version = "0.19.2" },
    { name = "hashbrown", version = "0.11.2" },
    { name = "parking_lot", version = "0.11.2" },
    { name = "parking_lot_core", version = "0.8.5" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "allow"